#!/bin/bash
#xrandr --dpi 90x90
xrandr --output eDP1 --right-of DP1
xmodmap standard.modmap
bspc monitor DP1 -d I II III IV V VI VII
bspc monitor eDP1 -d VIII IX X
cp /home/fabian/run/tlp_ac /etc/default/tlp
feh --bg-fill $HOME/wallpaper/sunset_tea_garden.jpg
echo "power on" | bluetoothctl
termite -e "bash -c 'sudo tlp start && cp /home/fabian/run/tlp_bat /etc/default/tlp'"
